### PR TITLE
add support for goldsrc servers

### PR DESCRIPTION
**Pull request by LAxBANDA**

### CODE REVIEW

**Comment by DemOnJR** [comment]
Tested
First https://pastebin.com/iRUe3Z9T
After https://pastebin.com/NUPYd4cc

**Comment by LAxBANDA** [comment]
@GiyoMoon considere merge to master branch please.

**Comment by LAxBANDA** [comment]
Test: 
`  {
    ip: '131.221.35.10:27011',
    name: '[BandaServers.CL] CS 1.6 Ryohazuki RIP',
    map: 'de_dust',
    folder: 'cstrike',
    game: 'Counter-Strike',
    players: 0,
    maxPlayers: 12,
    protocol: 47,
    serverType: 'd',
    environment: 'l',
    visibility: 0,
    mod: 0,
    vac: 1,
    bots: 0
  },`

**Comment by LAxBANDA** [comment]
anyone reply?

**Comment by DemOnJR** [comment]
> anyone reply?

i think that this rep is dead

**Comment by LAxBANDA** [comment]
> > anyone reply?
> 
> i think that this rep is dead
hello, i have published a new version in the following https://github.com/LAxBANDA/steam-server-query-goldsrc-support

**Pull request closed without merging**
